let knightRig=null;const enemyRigs={};const knightReady=(async()=>{const pose=await(await fetch('knight-parts/pose.json?v=slash2')).json();await Promise.all([1,2,3].map(async variant=>{const folder=variant===3?'knight-parts/':'enemy-parts/variant-'+variant+'/';const rig={...pose};rig.images=await Promise.all(rig.files.map(f=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=reject;im.src=folder+encodeURIComponent(f.name);})));enemyRigs[variant]=rig;}));if(typeof loadMonsterRigs==='function')await loadMonsterRigs();knightRig=enemyRigs[3];})();
function drawReadableBoss(ctx,g,x,y){if(!knightRig)return;const rigScale=.32*(g.visualStyle?.scale||1),r=g.visualRig||knightRig,a=g.attack,q=a?Math.max(0,(g.time-a.start)/(a.impact-a.start)):0,kind=a?.kind;
const prep=Math.min(1,q/.32),strike=Math.max(0,Math.min(1,(q-.9)/.2)),recovery=Math.max(0,Math.min(1,(q-1.12)/.28)),weight=prep*(1-recovery);
const release=Math.max(0,(q-.68)*1800),blend=Math.min(1,release/100);const refs=!g.visualStyle?.family&&q>=.68?(r.slash.filter(f=>f.time<=Math.min(399,release)).at(-1)?.refs||r.refs):r.refs;let shoulder=0,elbow=0,lean=0,drop=0;
if(kind==='jump'){const slam=Math.min(1,Math.max(0,(q-.58)/.14));shoulder=160*weight-150*slam*(1-recovery);elbow=20*weight;lean=12*slam*(1-recovery);drop=12*weight+16*slam*(1-recovery);}
if(kind==='up'){shoulder=-80*weight+145*strike*(1-recovery);elbow=-35*weight;lean=-12*weight;}
if(kind==='down'){shoulder=160*weight-165*strike*(1-recovery);elbow=20*weight;lean=3*weight;}
lean*=g.visualStyle?.lean??1;let custom=g.visualStyle?.family?enemyMotion(g.visualStyle.family,kind,q,g.time):null;if(g.meleePreview){custom=meleeMotion(g.meleePreview,q);y+=custom.vertical;}if(custom){lean=custom.lean;drop=custom.drop;x+=custom.shift;}
const combine=(t,p)=>{if(!p)return t;const rad=p.angle*Math.PI/180,c=Math.cos(rad),s=Math.sin(rad),lx=t.x*p.scale_x,ly=t.y*p.scale_y;return {...t,x:p.x+c*lx-s*ly,y:p.y+s*lx+c*ly,angle:p.angle+t.angle,scale_x:p.scale_x*t.scale_x,scale_y:p.scale_y*t.scale_y,a:p.a*t.a};};
const sample=n=>{const p=n.pose;return {...p,x:+(p.x||0),y:+(p.y||0),angle:+(p.angle||0),scale_x:+(p.scale_x||1),scale_y:+(p.scale_y||1),a:+(p.a??1)};};
const bones={};for(const n of refs.filter(n=>n.type==='bone_ref')){const t=sample(n);if(['bone_000','bone_002'].includes(n.name))t.angle+=(kind==='down'&&n.name==='bone_002'?-22*weight:shoulder)*(1-blend);if(['bone_001','bone_003'].includes(n.name))t.angle+=(kind==='down'&&n.name==='bone_003'?-35*weight:elbow)*(1-blend);if(g.visualStyle?.brace&&kind==='up'&&n.name==='bone_002')t.angle+=18*weight*(1-blend);if(n.name==='bone_006')t.y-=drop*(1-blend); if(custom){const base=sample(n);t.angle=base.angle+({bone_000:custom.right,bone_001:custom.re,bone_002:custom.left,bone_003:custom.le}[n.name]||0);if(n.name==='bone_006')t.y=base.y-custom.drop;if(n.name==='bone_004')t.angle+=custom.stride*16;if(n.name==='bone_005')t.angle-=custom.stride*16;}bones[n.ref.id]=combine(t,bones[n.ref.parent]);}
ctx.save();ctx.translate(x,y+6);ctx.fillStyle='#34584a44';ctx.beginPath();ctx.ellipse(0,0,52,12,0,0,Math.PI*2);ctx.fill();ctx.rotate(-lean*Math.PI/180);ctx.scale(-rigScale,-rigScale);
for(const n of refs.filter(n=>n.type==='object_ref').sort((a,b)=>(a.name==='Sword'?8.5:+a.ref.z_index)-(b.name==='Sword'?8.5:+b.ref.z_index))){if(n.name==='SlashFX')continue;const t=combine(sample(n),bones[n.ref.parent]);if(n.name==='Sword'){t.a=1;const readyAngle=kind==='jump'?90:kind==='down'?90:kind==='up'?180:0;t.angle=kind==='jump'?90-180*Math.min(1,Math.max(0,(q-.58)/.14)):readyAngle*weight*(1-blend)+t.angle*blend;if(custom){t.angle=custom.wa;if(g.visualStyle.scale&&g.visualStyle.weapon!=='fist'){t.scale_x/=g.visualStyle.scale;t.scale_y/=g.visualStyle.scale;}} const hn=refs.find(n=>n.name==='Right Hand'),h=combine(sample(hn),bones[hn.ref.parent]),hr=h.angle*Math.PI/180,wr=t.angle*Math.PI/180;const hx=h.x+Math.cos(hr)*72*h.scale_x+Math.sin(hr)*64*h.scale_y,hy=h.y+Math.sin(hr)*72*h.scale_x-Math.cos(hr)*64*h.scale_y;t.x=hx-(Math.cos(wr)*63*t.scale_x+Math.sin(wr)*62*t.scale_y);t.y=hy-(Math.sin(wr)*63*t.scale_x-Math.cos(wr)*62*t.scale_y);}if(n.name==='Left Hand'){const hr=t.angle*Math.PI/180,lx=t.x+Math.cos(hr)*64*t.scale_x+Math.sin(hr)*64*t.scale_y,ly=t.y+Math.sin(hr)*64*t.scale_x-Math.cos(hr)*64*t.scale_y,cr=Math.cos(-lean*Math.PI/180),sr=Math.sin(-lean*Math.PI/180);g.freeHand={x:x-rigScale*(cr*lx-sr*ly),y:y+6-rigScale*(sr*lx+cr*ly)};}const f=r.files[+t.file],im=r.images[+t.file];ctx.save();ctx.globalAlpha*=t.a;ctx.translate(t.x,t.y);ctx.rotate(t.angle*Math.PI/180);ctx.scale(t.scale_x,-t.scale_y);if(n.name==='Sword'){const rad=t.angle*Math.PI/180,lx=t.x+Math.cos(rad)*(g.visualStyle?.weapon==='fist'?72:350)*t.scale_x+Math.sin(rad)*62*t.scale_y,ly=t.y+Math.sin(rad)*(g.visualStyle?.weapon==='fist'?72:350)*t.scale_x-Math.cos(rad)*62*t.scale_y,cr=Math.cos(-lean*Math.PI/180),sr=Math.sin(-lean*Math.PI/180);g.bladeTip={x:x-rigScale*(cr*lx-sr*ly),y:y+6-rigScale*(sr*lx+cr*ly)};}const px=+(t.pivot_x??f.pivot_x??0),py=+(t.pivot_y??f.pivot_y??1);if(n.name==='Sword'&&g.visualStyle?.weapon)drawPluginWeapon(ctx,g.visualStyle.weapon);else ctx.drawImage(im,-im.width*px,-im.height*(1-py));if(g.visualStyle?.outfit)drawEnemyPlugin(ctx,n.name,g.visualStyle);ctx.restore();}ctx.restore();
}

function drawBossWave(ctx,g){const a=g.attack;if(!a||!knightRig)return;const q=(g.time-a.start)/(a.impact-a.start);if(a.kind==='jump'){drawGroundWave(ctx,g,q);return;}if(q<.68||q>1.25)return;const im=(g.visualRig||knightRig).images[10];if(!a.waveOrigin)a.waveOrigin={...(g.bladeTip||{x:630,y:345})};const travel=Math.min(1.5,(q-.72)/.28),grow=Math.max(.12,Math.min(1,(q-.68)/.12)),origin=a.waveOrigin;ctx.save();ctx.globalAlpha=q>1.08?Math.max(0,(1.25-q)/.17):.85;
if(q<.72){ctx.translate(origin.x,origin.y);ctx.scale(-1,1);if(g.visualStyle?.fx)drawMonsterProjectile(ctx,g.visualStyle,-38,-45,76,90,q);else ctx.drawImage(im,-38,-45,76,90);}else if(a.kind==='jump'){const cx=origin.x+(410-origin.x)*travel,cy=origin.y+(402.5-origin.y)*Math.min(1,travel*2);ctx.translate(cx,cy);ctx.rotate(Math.PI/2);ctx.drawImage(im,40,12,415,472,-171*grow,-170*grow,342*grow,340*grow);}else{const targetY=a.kind==='up'?572:416,cx=origin.x+(145-origin.x)*travel,cy=origin.y+(targetY-origin.y)*Math.min(1,travel*2);ctx.translate(cx,cy);ctx.scale(-1,1);if(g.visualStyle?.fx)drawMonsterProjectile(ctx,g.visualStyle,-55*grow,-156*grow,110*grow,312*grow,q);else ctx.drawImage(im,-55*grow,-156*grow,110*grow,312*grow);}ctx.restore();}

function drawGroundWave(ctx,g,q){const a=g.attack;if(q<.72||q>1.25)return;if(!a.groundOrigin)a.groundOrigin={...(g.bladeTip||{x:610,y:425})};const origin=a.groundOrigin,t=(q-.72)/.28,front=origin.x+(90-origin.x)*t,fade=q>1.08?Math.max(0,(1.25-q)/.17):1;ctx.save();ctx.globalAlpha=fade;
// A thin ridge follows the floor plane continuously through the three lanes.
ctx.fillStyle='#74665038';ctx.beginPath();ctx.moveTo(front,260);ctx.lineTo(origin.x,260);ctx.lineTo(origin.x,768);ctx.lineTo(front,768);ctx.closePath();ctx.fill();
const curve=()=>{ctx.beginPath();ctx.moveTo(front+18,260);ctx.bezierCurveTo(front-18,386,front-18,550,front+18,768);};curve();ctx.strokeStyle='#463f35aa';ctx.lineWidth=17;ctx.stroke();curve();ctx.strokeStyle=g.visualStyle?.waveColor||'#c28b52';ctx.lineWidth=10;ctx.stroke();curve();ctx.strokeStyle='#fff0b8';ctx.lineWidth=3;ctx.stroke();
for(let j=0;j<25;j++){const yy=270+j*18,xx=front+18-30*Math.sin(Math.PI*(yy-260)/468);ctx.fillStyle=j%2?'#c9b593bb':'#e8d8b8bb';ctx.beginPath();ctx.ellipse(xx+10+Math.sin(j*2+t*4)*7,yy-7,8+(j%3)*2,4,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#75634d77';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(xx+15,yy+3);ctx.lineTo(xx+35,yy+8);ctx.lineTo(xx+48,yy+4);ctx.stroke();}
if(g.visualStyle?.fx)drawMonsterGroundDetails(ctx,g.visualStyle,front,q);if(q<.83){const k=(q-.72)/.11;ctx.fillStyle='#ffe4aa';ctx.beginPath();ctx.ellipse(origin.x,origin.y,12+25*k,5+9*k,0,0,Math.PI*2);ctx.fill();for(let j=0;j<8;j++){ctx.fillStyle='#d3b58b';ctx.beginPath();ctx.arc(origin.x+Math.cos(j)*k*45,origin.y-Math.abs(Math.sin(j))*k*35,3,0,Math.PI*2);ctx.fill();}}ctx.restore();}
