// Resume the same combat timeline; do not reroll or discard an in-flight turn.
const COMBAT_SAVE_FIELDS=['stamina','staminaMax','opening','guardianUsed','elementState','resolveUsed','recoveryPerfects','recoveryUsed','damageScale','time','combo','attack','action','counter','shots','lastCombo','damageEvents','skillEvents','lastBonuses','enemyRecoveryUntil','armor','chainArmor','armorBroken','armorRecovery','pendingGuard','heavyWindow','heavyChosen','daggerWindow','bowSpent','pendingWeaponBonus','nextSwordBonus','faultUsed','echoPending','lastCritical','weaponMotion','cancelReturn','interruptMotion','deflectMotion','bossShownPhase','phaseTransition','hurtTime','deathTime','lossTime','weaponTechniqueEvents'];
function combatSnapshot(g){const fields={};for(const key of COMBAT_SAVE_FIELDS)fields[key]=g[key]??null;return {version:1,weapon:g.weapon,enemy:g.enemyId,state:g.state,fields,identitySeen:[...(g.identitySeen||[])],burnComboApplied:!!g.lastCombo&&g.lastCombo===g.burnLastCombo};}
function validCombatSnapshot(s,run){return !!s&&s.version===1&&s.weapon===run.weapon&&s.enemy===run.enemyId&&s.state===run.state&&Number.isFinite(s.fields?.time)&&s.fields.time>=0&&Array.isArray(s.fields.shots)&&s.fields.shots.length<=30&&(!s.fields.combo||Array.isArray(s.fields.combo.hits)&&s.fields.combo.hits.length<=4&&Number.isInteger(s.fields.combo.index)&&s.fields.combo.index>=0&&s.fields.combo.index<=s.fields.combo.hits.length)&&Array.isArray(s.identitySeen);}
const timelinePersist=CampaignGame.prototype.persist;
CampaignGame.prototype.persist=function(){timelinePersist.call(this);if(this.checkpointUpdating)this.checkpointDirty=true;if(!this.test&&this.savedRun){this.savedRun.combatSnapshot=combatSnapshot(this);try{localStorage.setItem('rogue-lane-checkpoint-v1',JSON.stringify(this.savedRun));}catch{}}};
const timelineResume=CampaignGame.prototype.resume;
CampaignGame.prototype.resume=function(){const run=this.savedRun,snapshot=run?.combatSnapshot,valid=validCombatSnapshot(snapshot,run||{});const ok=timelineResume.call(this);if(ok&&valid){for(const key of COMBAT_SAVE_FIELDS)this[key]=snapshot.fields[key];this.identitySeen=new Set(snapshot.identitySeen);this.burnLastCombo=snapshot.burnComboApplied?this.lastCombo:null;this.feedback='Tiếp tục đúng nhịp đã lưu';this.checkpointSavedAt=this.time;this.persist();}return ok;};
const timelineUpdate=CampaignGame.prototype.update;
CampaignGame.prototype.update=function(dt){this.checkpointUpdating=true;this.checkpointDirty=false;try{timelineUpdate.call(this,dt);}finally{this.checkpointUpdating=false;}if(!this.test&&['combat','reward'].includes(this.state)&&(this.checkpointDirty||this.time-(this.checkpointSavedAt??-Infinity)>=.25)){this.checkpointSavedAt=this.time;this.persist();}};
for(const method of ['beginChain','act','deflect','weaponAction']){const original=CampaignGame.prototype[method];CampaignGame.prototype[method]=function(...args){const ok=original.apply(this,args);if(ok&&!this.test)this.persist();return ok;};}

