// Progress is derived from permanent meta, never from temporary Test Mode ranks.
let collectionTab='bow',collectionSignature='',collectionFilter='all',collectionGroup='all',collectionPage=0;
const WEAPON_GLYPHS={bow:'M12 4Q34 24 12 44M12 4V44M8 24H39M32 18l7 6-7 6',katana:'M12 40L37 7l4 4-29 33M8 32l12 10',daggers:'M8 7l16 19-5 5L4 12ZM39 7L23 26l5 5 16-19M12 35l6 7m18-7-6 7',greatsword:'M22 34V6h7v28M13 34h25M25 35v10',shared:'M24 5l7 12 13 7-13 7-7 13-7-13-13-7 13-7Z'};
function weaponIcon(id){return `<svg viewBox="0 0 48 48" aria-hidden="true"><path d="${WEAPON_GLYPHS[id]}" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/></svg>`;}
function collectionProgress(meta,id){const extra=typeof extraProgress==='function'?extraProgress(meta,id):null;if(extra)return extra;if(id==='momentum')return [meta.perfect,12,'Perfect'];if(id==='guardian')return [meta.clean,3,locale==='vi'?'Trận không mất HP':'Encounters without HP loss'];if(id==='bloodlust')return [meta.elite,1,locale==='vi'?'Elite không mất HP':'Elite without HP loss'];return [1,1,locale==='vi'?'Mở sẵn':'Available from start'];}
function renderCollection(){
 const pageSize=window.innerHeight>=980?6:4;
 const signature=pageSize+collectionPage+locale+collectionTab+collectionFilter+collectionGroup+JSON.stringify(game.meta);if(signature===collectionSignature)return;collectionSignature=signature;
 const root=$('#collection-content');root.replaceChildren();const tabs=document.createElement('div');tabs.className='collection-tabs';tabs.setAttribute('role','tablist');
 for(const id of [...Object.keys(WEAPONS),'shared']){const b=document.createElement('button');b.id='collection-tab-'+id;b.setAttribute('role','tab');b.setAttribute('aria-label',id==='shared'?(locale==='vi'?'Chiến kỹ':'Battle Arts'):weaponLabel(id));b.tabIndex=id===collectionTab?0:-1;b.onkeydown=e=>{const ids=[...Object.keys(WEAPONS),'shared'],i=ids.indexOf(id),next=e.key==='ArrowRight'?(i+1)%ids.length:e.key==='ArrowLeft'?(i+ids.length-1)%ids.length:e.key==='Home'?0:e.key==='End'?ids.length-1:-1;if(next<0)return;e.preventDefault();collectionTab=ids[next];collectionPage=0;renderCollection();document.getElementById('collection-tab-'+collectionTab).focus();};b.setAttribute('aria-selected',String(id===collectionTab));b.setAttribute('aria-controls','collection-skills');b.innerHTML=weaponIcon(id)+`<span>${id==='shared'?(locale==='vi'?'Chiến kỹ':'Battle Arts'):weaponLabel(id)}</span>`;b.onclick=()=>{collectionTab=id;collectionPage=0;renderCollection();document.getElementById(b.id).focus();};tabs.append(b);}root.append(tabs);const guides=document.createElement('div');guides.className='collection-guide-links';for(const id of [...Object.keys(WEAPONS),'shared']){const cell=document.createElement('div');if(id!=='shared'){const detail=document.createElement('button');detail.textContent=locale==='vi'?'Chi tiết':'Details';detail.setAttribute('aria-label',(locale==='vi'?'Chi tiết ':'Details: ')+weaponLabel(id));detail.onclick=()=>showWeaponGuide(id);cell.append(detail);}guides.append(cell);}root.append(guides);
 const list=document.createElement('div');list.id='collection-skills';list.setAttribute('role','tabpanel');list.setAttribute('aria-labelledby','collection-tab-'+collectionTab);root.append(list);
 const rows=collectionTab==='shared'?Object.keys(SKILLS).filter(id=>!EXTRA_SKILLS[id]?.weapon).map(id=>({id,title:skillLabel(id),descs:SKILLS[id].desc,progress:collectionProgress(game.meta,id),icon:skillIconMarkup(id)})):WEAPONS[collectionTab].upgrades.map((desc,i)=>({id:collectionTab+i,title:desc.split(':')[0],descs:[desc.split(':').slice(1).join(':').trim()],progress:[game.meta.xp[collectionTab]||0,i?20:8,'XP'],icon:weaponIcon(collectionTab)}));
 if(collectionTab!=='shared')for(const [id,v]of Object.entries(EXTRA_SKILLS)){if(v.weapon===collectionTab)rows.push({id,title:skillLabel(id),descs:SKILLS[id].desc,progress:extraProgress(game.meta,id),icon:skillIconMarkup(id)});}
 const controls=document.createElement('div');controls.className='collection-controls';
 function filters(options,current,change){const bar=document.createElement('div');bar.className='collection-filters';for(const [id,vi,en]of options){const button=document.createElement('button');button.textContent=locale==='vi'?vi:en;button.setAttribute('aria-pressed',String(id===current));button.onclick=()=>{change(id);collectionPage=0;renderCollection();};bar.append(button);}controls.append(bar);}
 filters([['all','Tất cả','All'],['open','Đã mở','Unlocked'],['locked','Chưa mở','Locked']],collectionFilter,id=>collectionFilter=id);
 if(collectionTab==='shared')filters([['all','Mọi nhóm','All groups'],['counter','Phản công','Counter'],['survival','Sinh tồn','Survival'],['element','Nguyên tố','Elements']],collectionGroup,id=>collectionGroup=id);
 root.insertBefore(controls,list);list.className='collection-grid';
 const visible=rows.filter(row=>{const open=row.progress[0]>=row.progress[1];return (collectionFilter==='all'||(collectionFilter==='open'?open:!open))&&(collectionTab!=='shared'||collectionGroup==='all'||collectionCategory(row.id)===collectionGroup);}).sort((a,b)=>Number(b.progress[0]>=b.progress[1])-Number(a.progress[0]>=a.progress[1]));
 const pages=Math.max(1,Math.ceil(visible.length/pageSize));collectionPage=Math.min(collectionPage,pages-1);list.style.setProperty('--collection-rows',pageSize/2);
 for(const row of visible.slice(collectionPage*pageSize,(collectionPage+1)*pageSize)){const [value,target]=row.progress,unlocked=value>=target,card=document.createElement('button');card.className='collection-skill'+(unlocked?' unlocked':'');card.innerHTML=`<div class="collection-icon">${row.icon}</div><h3>${row.title}</h3><span class="unlock-status">${locale==='vi'?(unlocked?'Đã mở':'Chưa mở'):(unlocked?'Unlocked':'Locked')}</span><progress max="${target}" value="${Math.min(value,target)}" aria-label="${row.title}"></progress><small>${Math.min(value,target)}/${target}</small>`;card.onclick=()=>showCollectionSkill(row);list.append(card);}
 if(!visible.length){const empty=document.createElement('p');empty.className='collection-empty';empty.textContent=locale==='vi'?'Không có chiến kỹ trong bộ lọc này.':'No skills match these filters.';list.append(empty);}
 const pager=document.createElement('div');pager.className='collection-pager';const back=document.createElement('button'),next=document.createElement('button'),label=document.createElement('span');back.textContent='‹';next.textContent='›';back.setAttribute('aria-label',locale==='vi'?'Trang trước':'Previous page');next.setAttribute('aria-label',locale==='vi'?'Trang sau':'Next page');back.disabled=collectionPage===0;next.disabled=collectionPage===pages-1;label.textContent=(collectionPage+1)+' / '+pages;label.setAttribute('aria-live','polite');for(const [button,delta]of [[back,-1],[next,1]])button.onclick=()=>{collectionPage+=delta;renderCollection();};pager.append(back,label,next);root.append(pager);
 const note=document.createElement('p');note.className='help';note.textContent=locale==='vi'?'Tự mở khi đủ tiến trình. Test Mode không ghi tiến trình.':'Unlocks automatically at the threshold. Test Mode does not add progress.';root.append(note);requestAnimationFrame(fitCollection);
}
function skillDemo(){game.enterTest('katana','iron_bear');game.enemyMax=game.enemyHp=200;game.testLength=1;game.testLevel=3;game.skills={flame_counter:2,momentum:1,guardian:1,focus:1};game.flow=2;auto=selfPlay=true;paused=false;nextAttack=game.time+.6;$('#drawer').close();syncToggles();}

function collectionCategory(id){return EXTRA_SKILLS[id]?.element?'element':['guardian','focus','resolve','second_wind'].includes(id)?'survival':'counter';}
function showCollectionSkill(row){
 let dialog=document.getElementById('collection-detail');if(!dialog){dialog=document.createElement('dialog');dialog.id='collection-detail';document.body.append(dialog);dialog.addEventListener('click',e=>{if(e.target!==dialog)return;const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();});}
 const [value,target,unit]=row.progress,open=value>=target,vi=locale==='vi';
 dialog.innerHTML=`<button class="collection-detail-close" aria-label="${vi?'Đóng':'Close'}">×</button><div class="collection-detail-icon">${row.icon}</div><h2>${row.title}</h2><span class="unlock-status">${vi?(open?'Đã mở':'Chưa mở'):(open?'Unlocked':'Locked')}</span><div class="collection-ranks">${row.descs.map((desc,i)=>`<p><strong>${row.descs.length>1?'Lv.'+(i+1):vi?'Tác dụng':'Effect'}</strong><br>${translateText(desc)}</p>`).join('')}</div><progress max="${target}" value="${Math.min(value,target)}"></progress><p>${vi?'Tiến trình mở khóa':'Unlock progress'}: ${Math.min(value,target)}/${target} · ${translateText(unit)}</p><p>${vi?'Phù hợp':'Fits'}: ${collectionAffinity(row.id)}</p>`;
 dialog.querySelector('button').onclick=()=>dialog.close();dialog.showModal();
}
function collectionAffinity(id){const vi=locale==='vi',weapon=EXTRA_SKILLS[id]?.weapon;if(weapon)return weaponLabel(weapon);for(const w of Object.keys(WEAPONS))if(id.startsWith(w))return weaponLabel(w);const hints={ember:vi?'Sát thương kéo dài':'Sustained damage',rime:vi?'Thêm thời gian đọc đòn':'More time to read attacks',spark:vi?'Phản công đều đặn':'Consistent counters',momentum:vi?'Giữ chuỗi Flow':'Maintaining Flow',bloodlust:vi?'Giữ chuỗi Flow dài':'Long Flow streaks',flame_counter:vi?'Né Perfect thường xuyên':'Frequent Perfect dodges',focus:vi?'Luyện timing né':'Practising dodge timing'};return hints[id]||(vi?'Mọi vũ khí':'All weapons');}

function showWeaponGuide(id){const vi=locale==='vi';const guides={
 bow:vi?['Cung · phản công tầm xa','Perfect tích Aim. Đủ 2 Aim, hoặc né Normal khi đang có Aim, phản công tiêu thụ Aim để tăng sát thương. Mũi tên chạm địch mới gây damage.','Ưu: dễ theo dõi, sát thương theo đợt.','Nhược: damage phụ thuộc Aim; có thời gian bay.']:['Bow · ranged counter','Perfect adds Aim. At 2 Aim, or on a Normal dodge with stored Aim, the counter spends Aim for damage. Damage lands when the arrow arrives.','Strength: readable, periodic burst.','Weakness: Aim-dependent damage; projectile delay.'],
 katana:vi?['Kiếm · phản đòn chính xác','Perfect tăng sát thương trực tiếp. Mastery Lv.2: mỗi 3 Perfect thêm 2 damage. Lv.3: Flow 3 trở lên thêm 1 damage.','Ưu: mạnh khi né chính xác liên tục.','Nhược: hụt timing làm mất phần lớn lợi thế.']:['Sword · precise counter','Perfect adds direct damage. Mastery Lv.2: every 3 Perfects add 2 damage. Lv.3: Flow 3+ adds 1 damage.','Strength: reliable with precise timing.','Weakness: much weaker without Perfect.'],
 daggers:vi?['Dao găm · chuỗi nhát nhanh','Normal tích 2 Hit; Perfect tích 3 (4 ở Mastery Lv.2). Mỗi đủ 4 Hit tiêu mốc đó để thêm 1 damage, hoặc 2 ở Lv.3. Hit hiện tại là tài nguyên, chưa gây damage riêng từng nhát.','Ưu: Normal vẫn tích tài nguyên; phản công nhanh.','Nhược: nhiều nhát chưa có tương tác nguyên tố riêng.']:['Daggers · fast flurry','Normal adds 2 Hits; Perfect adds 3 (4 at Mastery Lv.2). Every 4 banked Hits add 1 damage, or 2 at Lv.3. Hits are currently a resource, not separate damage events.','Strength: Normal still builds resources; fast counters.','Weakness: micro-hits lack separate elemental interactions.'],
 greatsword:vi?['Đại kiếm · tích Charge','Normal, hoặc Perfect khi chưa có Charge, tích 1 Charge. Perfect khi đã có Charge sẽ tiêu thụ toàn bộ Charge để tăng damage. Giới hạn 2 Charge, 3 ở Mastery Lv.2.','Ưu: đòn xả mạnh; Normal vẫn tích Charge.','Nhược: phản công chậm; Perfect xả sớm nên khó tích đầy.']:['Greatsword · stored Charge','Normal, or Perfect with no Charge, adds 1 Charge. Perfect with stored Charge spends it all for damage. Capacity is 2, or 3 at Mastery Lv.2.','Strength: burst damage; Normal builds Charge.','Weakness: slow counter; Perfect releases early.']};
 const g=guides[id];if(!g)return;showCollectionSkill({id,title:g[0],icon:weaponIcon(id),descs:[g[1]],progress:[game.meta.xp[id]||0,20,'XP']});const dialog=document.getElementById('collection-detail');dialog.querySelector('.collection-ranks').insertAdjacentHTML('beforeend',`<p>${g[2]}<br>${g[3]}</p>`);dialog.querySelector('.unlock-status').textContent=vi?'Cơ chế bản hiện tại':'Current mechanics';dialog.querySelector('progress').remove();dialog.querySelectorAll(':scope > p').forEach(p=>p.remove());}

if(typeof window!=='undefined')window.addEventListener('resize',()=>{collectionSignature='';if(!document.getElementById('collection-panel').hidden)renderCollection();});

function fitCollection(){const drawer=document.getElementById('mastery-dialog'),grid=document.getElementById('collection-skills');if(!drawer.open||!grid||document.getElementById('collection-panel').hidden)return;const style=getComputedStyle(drawer);let used=Number.parseFloat(style.paddingTop)+Number.parseFloat(style.paddingBottom);for(const child of drawer.children){if(getComputedStyle(child).display==='none')continue;const cs=getComputedStyle(child);used+=child.getBoundingClientRect().height+Number.parseFloat(cs.marginTop||0)+Number.parseFloat(cs.marginBottom||0);}const rows=Number(grid.style.getPropertyValue('--collection-rows'))||2,available=drawer.clientHeight-used+grid.getBoundingClientRect().height-12;const height=Math.max(94,Math.min(210,Math.floor((available-(rows-1)*9)/rows)));grid.classList.toggle('compact-cards',height<130);grid.style.setProperty('--collection-row-height',height+'px');grid.style.setProperty('--collection-icon-size',Math.max(32,Math.min(72,Math.floor(height*.35)))+'px');}

function openMastery(){const dialog=document.getElementById('mastery-dialog');document.getElementById('collection-panel').hidden=false;if(!dialog.open)dialog.showModal();collectionSignature='';renderCollection();}
function closeMastery(){document.getElementById('mastery-dialog').close();document.getElementById('collection-panel').hidden=true;}
if(typeof document!=='undefined'){
document.getElementById('close-mastery').onclick=closeMastery;
document.getElementById('mastery-dialog').addEventListener('cancel',()=>{document.getElementById('collection-panel').hidden=true;});
document.getElementById('mastery-dialog').addEventListener('click',e=>{if(e.target!==e.currentTarget)return;const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeMastery();});

}
