// Shared gameplay presentation: no change to hit validation or combo schedule.
Object.assign(GameAudio.files,{deflectA:'deflect-user-1.mp3',deflectB:'deflect-user-2.mp3',deflectC:'deflect-user-3.mp3'});
const contactStyle=document.createElement('style');contactStyle.textContent='#boss-combat-hud{width:calc((100% - 162px)/2);min-width:108px;max-width:170px}.boss-title-row strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:10px}.boss-title-row{gap:3px}';document.head.append(contactStyle);
function deflectTravel(g){const m=g.deflectMotion;if(!m?.valid||g.time<m.start||g.time>m.end)return null;const smooth=v=>{v=Math.max(0,Math.min(1,v));return v*v*(3-2*v);};const arrival=smooth((g.time-m.start)/Math.max(.001,Math.min(m.lane!==1?.012:.04,(m.impact-m.start)*.3))),returning=smooth((g.time-m.impact)/.32),weight=arrival*(1-returning);const verticalWeight=m.lane!==1?1-returning:weight;return {weight,lane:m.lane,x:90+80*weight,feet:554+(m.lane-1)*156*verticalWeight};}
const contactActor=actor;actor=function(role,x,feet,state,clock){if(role==='hero'){const p=deflectTravel(game);if(p){x=p.x;feet=p.feet;state='idle';if(heroRig&&game.bladeTip)heroRig.contactPoint={x:(game.bladeTip.x-x)/.345,y:(feet+6-game.bladeTip.y)*arenaYScale/.345};}}contactActor(role,x,feet,state,clock);};
const contactMelee=meleeMotion;meleeMotion=function(g,q){const pose=contactMelee(g,q),travel=deflectTravel(g);return pose;};
// Draw expressions in the existing face socket, so sweat and injury follow every pose.
function prepareHealthFaces(r){const i=r.files.findIndex(f=>f.name.startsWith('Face ')),original=r.images[i];r.healthFaces=[null,null,null,original];for(const hp of [2,1]){const face=document.createElement('canvas');face.width=320;face.height=240;const c=face.getContext('2d');c.drawImage(original,0,0);c.globalCompositeOperation='source-atop';c.fillStyle=hp===1?'#84b7a37a':'#b9897340';c.fillRect(0,0,320,240);c.globalCompositeOperation='source-over';c.strokeStyle='#574344';c.lineWidth=7;c.lineCap='round';c.beginPath();c.moveTo(87,112);c.lineTo(127,98);c.moveTo(205,98);c.lineTo(245,112);c.stroke();c.fillStyle=hp===1?'#b4b9a7':'#c8b0a0';c.beginPath();c.ellipse(169,172,25,11,0,0,Math.PI*2);c.fill();c.strokeStyle='#785956';c.lineWidth=6;c.beginPath();c.moveTo(151,172);c.quadraticCurveTo(168,159,187,172);c.stroke();if(hp===1){c.fillStyle='#76528fa6';c.beginPath();c.ellipse(226,130,34,26,-.2,0,Math.PI*2);c.fill();c.fillStyle='#a08da8';c.beginPath();c.ellipse(226,123,26,16,0,0,Math.PI*2);c.fill();c.strokeStyle='#574344';c.lineWidth=7;c.beginPath();c.moveTo(203,124);c.quadraticCurveTo(223,134,245,122);c.stroke();c.save();c.translate(106,163);c.rotate(-.45);c.fillStyle='#e5d6b8';c.strokeStyle='#847866';c.lineWidth=3;c.fillRect(-32,-12,64,24);c.strokeRect(-32,-12,64,24);c.fillStyle='#c4ae89';c.fillRect(-8,-8,16,16);c.restore();c.strokeStyle='#ae544e';c.lineWidth=5;c.beginPath();c.moveTo(202,135);c.lineTo(223,152);c.moveTo(199,151);c.lineTo(219,169);c.stroke();}r.healthFaces[hp]=face;}return r;}
const contactRigDraw=HeroRig.prototype.draw;HeroRig.prototype.draw=function(c,x,feet,state,clock){if(!this.healthFaces)prepareHealthFaces(this);if(this.healthFaces)this.files.forEach((f,i)=>{if(f.name.startsWith('Face '))this.images[i]=this.healthFaces[Math.max(1,Math.min(3,this.hp||3))];});c.save();if(state==='idle'&&this.hp<3){c.translate(x,feet);c.rotate(this.hp===1?-.13:-.06);c.translate(-x,-feet);}contactRigDraw.call(this,c,x,feet,state,clock);c.restore();};
const soundSetting=document.createElement('label');soundSetting.textContent='Deflect · 3 nhịp';const soundListen=document.createElement('button');soundListen.textContent='Nghe 3 nhịp';soundListen.onclick=async()=>{effects.unlock();await Promise.all(['deflectA','deflectB','deflectC'].map(id=>effects.audio?.load(id)));for(let i=0;i<3;i++)effects.audio?.sample(['deflectA','deflectB','deflectC'][i],effects.volume*.14,i*.4,1);};soundSetting.append(soundListen);document.querySelector('#drawer details').append(soundSetting);