const WEAPONS={bow:{name:'Bow',state:'Aim',upgrades:['Steady Aim: Perfect tích 2 Aim','Piercing Shot: tiêu Aim thêm 1 damage']},katana:{name:'Kiếm',state:'Perfect',upgrades:['Iaido: mỗi 3 Perfect thêm 2 damage','Flow Edge: Flow 3 thêm 1 damage']},daggers:{name:'Daggers',state:'Hit bank',upgrades:['Flurry: Perfect có 4 hit','Serrated: mỗi 4 hit thêm 2 damage']},greatsword:{name:'Greatsword',state:'Charge',upgrades:['Deep Charge: chứa 3 Charge','Crushing Release: xả đầy thêm 1 damage']}};
const SKILLS={flame_counter:{name:'Flame Counter',desc:['Mỗi 2 Perfect thêm 1 damage','Mỗi Perfect thêm 1 damage']},focus:{name:'Focus',desc:['Perfect rộng thêm 0,04 giây','Perfect rộng thêm 0,08 giây']},momentum:{name:'Momentum',desc:['Flow 3 thêm 1 damage','Flow 2 thêm 1 damage']},guardian:{name:'Guardian',desc:['Nhận 1 shield cho lượt chơi','Hồi 1 shield mỗi encounter']},bloodlust:{name:'Bloodlust',desc:['Flow 4 thêm 1 damage','Flow 3 thêm 1 damage']}};
const ENEMIES={swordsman:{name:'Swordsman',variant:1,hp:6,windup:1.3,pattern:['up','down','jump']},heavy_knight:{name:'Heavy Knight',variant:3,hp:8,windup:1.5,pattern:['jump','up','up','down']},rogue:{name:'Rogue',variant:2,hp:7,windup:1.1,pattern:['down','jump','up','jump']},duelist:{name:'Elite Duelist',variant:1,hp:10,windup:1.0,pattern:['down','up','jump','down']}};
const BOSSES={executioner:{name:'Executioner',variant:3,hp:18,windup:1.2,pattern:['up','jump','down'],phases:2},warden:{name:'Iron Warden',variant:1,hp:22,windup:1.4,pattern:['jump','jump','up','down'],phases:2},wraith:{name:'Wraith',variant:2,hp:16,windup:1.0,pattern:['down','up','jump','up'],phases:3}};
const ROUTE=[['swordsman','heavy_knight'],['rest','shrine'],['rogue','shop'],['duelist'],['boss']];
class FullGame extends LaneGame {
 constructor(){super();this.meta={xp:{bow:0,katana:0,daggers:0,greatsword:0},gold:0,perfect:0,clean:0,elite:0,wins:0};try{const saved=JSON.parse(localStorage.getItem('rogue-lane-main-v1'));if(saved){for(const key of ['gold','perfect','clean','elite','wins'])if(Number.isFinite(saved[key]))this.meta[key]=Math.max(0,Math.floor(saved[key]));for(const id of Object.keys(WEAPONS))if(Number.isFinite(saved.xp?.[id]))this.meta.xp[id]=Math.max(0,Math.floor(saved.xp[id]));}}catch{}this.weapon='bow';this.test=false;this.bossId='executioner';this.reset();this.state='menu';this.savedRun=null;try{const run=JSON.parse(localStorage.getItem('rogue-lane-checkpoint-v1'));if(run&&WEAPONS[run.weapon]&&['starter','route','combat','reward','shop','shrine'].includes(run.state)&&Number.isInteger(run.floor)&&run.floor>=0&&run.floor<5&&Number.isFinite(run.hp)&&run.hp>0&&run.hp<=3)this.savedRun=run;}catch{}}
 reset(){super.reset();this.state='menu';this.floor=0;this.skills={};this.shield=0;this.aim=0;this.charge=0;this.bank=0;this.flow=0;this.perfects=0;this.counter=null;this.shots=[];this.damageEvents=[];this.enemyHp=6;this.enemyMax=6;this.isBoss=false;this.deathTime=null;this.hurtTime=-100;this.lossTime=null;this.lastDamage=0;this.totalDamage=0;this.attackCount=0;this.encounterHits=0;this.log=[];this.runGold=0;this.runXP=0;this.enemyId='swordsman';}
 get level(){if(this.test)return this.testLevel||1;const xp=this.meta?.xp[this.weapon]||0;return xp>=20?3:xp>=8?2:1;}
 get enemy(){return this.isBoss?BOSSES[this.enemyId]:ENEMIES[this.enemyId];}
 get phase(){if(!this.isBoss)return 1;const ratio=this.enemyHp/this.enemyMax;return ratio<=.33&&this.enemy.phases===3?3:ratio<=.5?2:1;}
 persist(){if(!this.test)try{localStorage.setItem('rogue-lane-main-v1',JSON.stringify(this.meta));if(['starter','route','combat','reward','shop','shrine'].includes(this.state)){const keys=['weapon','floor','hp','skills','shield','aim','charge','bank','flow','perfects','enemyId','isBoss','enemyHp','enemyMax','encounterHits','lastDamage','totalDamage','dodged','hits','runGold','runXP','log','state','bossId'];const run={};for(const key of keys)run[key]=this[key];this.savedRun=run;localStorage.setItem('rogue-lane-checkpoint-v1',JSON.stringify(run));}else if(['won','lost'].includes(this.state)){this.savedRun=null;localStorage.removeItem('rogue-lane-checkpoint-v1');}}catch{}}
 unlocked(id){return ['focus','flame_counter'].includes(id)||id==='momentum'&&this.meta.perfect>=12||id==='guardian'&&this.meta.clean>=3||id==='bloodlust'&&this.meta.elite>=1;}
 start(weapon=this.weapon){if(!WEAPONS[weapon])return false;this.reset();this.weapon=weapon;this.test=false;this.state='starter';this.persist();return true;}
 enterTest(weapon='bow',enemy='swordsman',boss=false){this.reset();this.weapon=WEAPONS[weapon]?weapon:'bow';this.test=true;this.skills={};this.loadEnemy(enemy,boss);return true;}
 loadEnemy(id,boss=false){if(!(boss?BOSSES:ENEMIES)[id])return false;this.enemyId=id;this.isBoss=boss;this.enemyMax=this.enemy.hp;this.enemyHp=this.enemyMax;this.attack=null;this.action=null;this.counter=null;this.shots=[];this.damageEvents=[];this.deathTime=null;this.encounterHits=0;this.attackCount=0;this.state='combat';if(this.skills.guardian>=2)this.shield=1;this.feedback='SẴN SÀNG • '+this.enemy.name;this.persist();return true;}
 selectNode(id){if(this.state!=='route'||!ROUTE[this.floor]?.includes(id))return false;this.log.push(id);if(id==='rest'){this.hp=Math.min(3,this.hp+1);this.floor++;this.state='route';this.persist();return true;}if(id==='shop'){this.state='shop';this.persist();return true;}if(id==='shrine'){this.state='shrine';this.persist();return true;}return this.loadEnemy(id==='boss'?this.bossId:id,id==='boss');}
 selectSkill(id){if(!SKILLS[id]||!this.unlocked(id)||(this.skills[id]||0)>=2)return false;if(this.state==='shop'&&this.meta.gold<2)return false;if(!['starter','reward','shop','shrine'].includes(this.state))return false;if(this.state==='shrine'&&!this.skills[id])return false;const prior=this.state;if(prior==='shop'){this.meta.gold-=2;this.persist();}this.skills[id]=(this.skills[id]||0)+1;if(id==='guardian')this.shield=1;if(prior!=='starter')this.floor++;this.state='route';this.persist();return true;}
 skip(){if(['reward','shop','shrine'].includes(this.state)){this.floor++;this.state='route';this.persist();return true;}return false;}
 begin(kind){if(this.state!=='combat'||this.counter||this.shots.some(s=>!s.hit)||!['up','down','jump'].includes(kind))return false;const ok=super.begin(kind);if(ok){const windup=Math.max(.8,this.enemy.windup-(this.phase-1)*.15);this.attack.impact=this.time+windup;this.attackCount++;}return ok;}
 resume(){if(!this.savedRun)return false;const run=this.savedRun;this.reset();this.test=false;for(const [key,value]of Object.entries(run))if(key in this)this[key]=value;this.attack=null;this.action=null;this.counter=null;this.shots=[];this.deathTime=this.state==='reward'?this.time-2:null;this.feedback='Tiếp tục lượt đã lưu';return true;}
 nextKind(){let pattern=this.enemy.pattern;if(this.isBoss&&this.phase===2)pattern=[...pattern].reverse();if(this.isBoss&&this.phase===3)pattern=[...pattern,'jump','down'];return pattern[this.attackCount%pattern.length];}
 act(kind){if(this.state!=='combat'||this.counter?.start!=null||!['up','down','jump'].includes(kind))return false;return super.act(kind);}
 damage(perfect,mutate=false){let damage=1,aim=this.aim,charge=this.charge,bank=this.bank,flow=this.flow+(perfect?1:0),count=this.perfects+(perfect?1:0);if(this.skills.momentum&&flow>=(this.skills.momentum>=2?2:3))damage++;if(this.skills.bloodlust&&flow>=(this.skills.bloodlust>=2?3:4))damage++;if(perfect&&this.skills.flame_counter&&(this.skills.flame_counter>=2||count%2===0))damage++;
 if(this.weapon==='bow'){if(perfect&&aim>=2||!perfect&&aim>0){damage+=aim+(this.level>=3?1:0);aim=0;}else if(perfect)aim=Math.min(2,aim+(this.level>=2?2:1));}
 if(this.weapon==='katana'){if(perfect)damage+=1+(this.level>=2&&count%3===0?2:0);if(this.level>=3&&flow>=3)damage++;}
 if(this.weapon==='daggers'){const hits=perfect?(this.level>=2?4:3):2;bank+=hits;damage+=Math.floor(bank/4)*(this.level>=3?2:1);bank%=4;}
 if(this.weapon==='greatsword'){const cap=this.level>=2?3:2;if(perfect&&charge>0){damage+=charge+(this.level>=3&&charge>=cap?1:0);charge=0;}else charge=Math.min(cap,charge+1);}
 if(mutate){this.aim=aim;this.charge=charge;this.bank=bank;this.flow=perfect?flow:0;this.perfects=count;}return damage;}
 update(dt){if(!Number.isFinite(dt)||dt<0)return;const dodged=this.dodged,hits=this.hits,attack=this.attack;super.update(dt);if(this.hits>hits){if(this.shield){this.shield--;this.hp++;this.feedback='SHIELD • chặn đòn';}else {this.encounterHits++;this.hurtTime=this.time;}this.flow=0;}if(this.hp<=0){this.state='lost';if(this.lossTime===null)this.lossTime=this.time;this.counter=null;this.shots=[];this.persist();return;}
 if(this.dodged>dodged){const p=this.pose(attack.impact),extra=(this.skills.focus||0)*.04/.9/2,perfect=p.progress>=.42-extra&&p.progress<=.58+extra;this.counter={perfect,start:null,released:false};if(perfect&&!this.test)this.meta.perfect++;this.feedback=perfect?'PERFECT • phản công':'NORMAL • phản công';}
 if(this.counter&&!this.action&&this.counter.start===null)this.counter.start=this.time;
 const release=this.weapon==='bow'?.5:this.weapon==='greatsword'?.52:this.weapon==='daggers'?.28:.35;
 if(this.counter?.start!=null&&!this.counter.released&&this.time>=this.counter.start+release){this.counter.released=true;this.shots.push({start:this.counter.start+release,impact:this.counter.start+release+(this.weapon==='bow'?.4:0),damage:this.damage(this.counter.perfect,true),perfect:this.counter.perfect});}
 if(this.counter?.start!=null&&this.time>=this.counter.start+.85)this.counter=null;
 for(const s of this.shots)if(!s.hit&&this.time>=s.impact&&this.state==='combat'){s.hit=true;this.lastDamage=s.damage;this.totalDamage+=Math.min(this.enemyHp,s.damage);this.enemyHp=Math.max(0,this.enemyHp-s.damage);this.damageEvents.push({time:s.impact,damage:s.damage,perfect:s.perfect});this.runXP++;if(!this.test){this.meta.xp[this.weapon]++;this.persist();}this.feedback=`${s.perfect?'PERFECT':'NORMAL'} • ${s.damage} DAMAGE`;if(this.enemyHp===0){this.attack=null;this.deathTime=s.impact;const gold=this.isBoss?10:this.enemyId==='duelist'?4:2;this.runGold+=gold;if(!this.test){this.meta.gold+=gold;if(this.encounterHits===0){this.meta.clean++;if(this.enemyId==='duelist')this.meta.elite++;}if(this.isBoss)this.meta.wins++;this.persist();}this.state=this.test?'test-won':this.isBoss?'won':'reward';this.feedback='THẮNG • '+this.enemy.name;this.persist();}}
 this.shots=this.shots.filter(s=>this.time-s.impact<.3);this.damageEvents=this.damageEvents.filter(e=>this.time-e.time<1.2);
 }
}
if(typeof module!=='undefined')module.exports={FullGame,WEAPONS,SKILLS,ENEMIES,BOSSES,ROUTE};

