const TERM_HELP={
 normal:{label:'Normal',vi:'Né an toàn nhưng chưa đúng cửa sổ Perfect. Thường ngắt Flow.',en:'A safe dodge outside the Perfect timing window. Usually breaks Flow.'},
 damage:{label:'Damage / DMG',vi:'Lượng HP đòn đánh làm đối thủ mất. Bonus skill được cộng vào damage khi kích hoạt.',en:'HP removed by a hit. Triggered skill bonuses add to its damage.'},
 xp:{label:'XP',vi:'Phản công trúng trong dungeon nhận 1 XP vũ khí. Test Mode không cộng XP.',en:'A dungeon counter hit earns 1 weapon XP. Test Mode grants no XP.'},
 gold:{label:'Gold',vi:'Tiền dùng mua skill hoặc vật tư. Giữ lại giữa các lượt dungeon.',en:'Currency for skills and supplies. Kept between dungeon runs.'},
 hp:{label:'HP',vi:'Máu của nhân vật. Hết HP thì lượt chơi kết thúc.',en:'Hero health. At zero HP, the run ends.'},
 lightning:{label:'Sét / Lightning',vi:'Tích đủ 3 phản công trúng: đòn thứ ba thêm tia Sét và damage. Không tính từng hit nhỏ của dao găm.',en:'At 3 counter hits, the third adds a spark and damage. Dagger micro-hits do not count separately.'},
 burn:{label:'Burn',vi:'Cháy gây damage khi chuỗi đòn kết thúc. Không cộng dồn và không kết liễu.',en:'Burn deals damage after the enemy chain. It neither stacks nor finishes an enemy.'},
 chill:{label:'Chill',vi:'Nhịp báo đòn đầu của chuỗi kế tiếp chậm hơn. Không bỏ lượt đối thủ.',en:'Slows the first tell of the next chain. Does not skip an enemy turn.'},
 hitbank:{label:'Hit bank',vi:'Dao găm tích hit vào bank. Đủ 4 hit thì tiêu 4 để cộng damage; phần dư giữ lại.',en:'Daggers bank hits. Every 4 hits are spent for bonus damage; leftovers carry over.'},
 flow:{label:'Flow',vi:'Chuỗi phản công Perfect. Normal thường ngắt Flow; trúng đòn luôn ngắt. Giữ đúng giữ Flow, không tăng.',en:'Consecutive Perfect counters. Normal usually breaks Flow; hits always do. Correct holds preserve it without adding Flow.'},
 perfect:{label:'Perfect',vi:'Né đúng thời điểm đòn chạm tới. Combo Perfect cần mọi nhịp né đều Perfect. Giữ đúng không tính Perfect.',en:'Dodge precisely as the hit arrives. A Perfect combo needs every dodge to be Perfect. Holding is not Perfect.'},
 mastery:{label:'Mastery',vi:'Độ thông thạo vũ khí. Phản công trúng nhận XP; 8/20 XP mở nâng cấp. Test Mode không cộng XP.',en:'Weapon proficiency. Counter hits earn XP; 8/20 XP unlock upgrades. Test Mode grants none.'},
 aim:{label:'Aim',vi:'Tích lực của cung: Perfect nạp Aim, lần phản công đủ điều kiện sau sẽ tiêu thụ Aim để tăng damage.',en:'Bow resource: Perfect counters build Aim; a later eligible counter spends it for bonus damage.'},
 charge:{label:'Charge',vi:'Lực tích của đại kiếm. Phản công nạp Charge; Perfect có Charge sẽ xả để tăng damage.',en:'Greatsword resource. Counters build Charge; a Perfect counter spends stored Charge for extra damage.'},
 shield:{label:'Shield',vi:'Chặn một lần mất HP. Shield không cộng dồn. Dù HP được bảo vệ, trúng đòn vẫn mất Flow.',en:'Blocks one instance of HP loss. Shields do not stack. Being hit still breaks Flow even if HP is protected.'},
 hold:{label:'Giữ đúng / Hold',vi:'Đứng yên khi đòn không chạm lane giữa. Né an toàn, giữ Flow hiện có, không nhận Perfect hoặc tăng Flow.',en:'Stay still when the attack misses the center lane. Safe holds preserve existing Flow but do not award Perfect or increase Flow.'},
 ice:{label:'Băng / Ice',vi:'Ba phản công trúng gây Chill: làm chậm nhịp báo đòn đầu của chuỗi kế tiếp. Không đóng băng hoàn toàn và không cho lượt đánh miễn phí.',en:'Three counter hits trigger Chill, slowing the first tell of the next chain. No full freeze or free attack turn.'},
 fire:{label:'Lửa / Fire',vi:'Ba phản công trúng gây cháy ngắn. Không cộng dồn cháy và không kết liễu: vẫn cần phản công cuối để hạ đối thủ.',en:'Three counter hits trigger a short burn. Burns do not stack or deliver the finishing blow; a final counter is still required.'}
};
TERM_HELP.deflect={label:'Deflect',vi:'Kiếm đỡ đòn cận chiến: bấm đúng lane phía enemy và đúng timing. Thành công giảm 2 Stamina; sai mất 1 tim.',en:'Sword melee guard: tap the enemy-side lane with correct timing. Removes 2 Stamina; a failed attempt costs a heart.'};
TERM_HELP.interrupt={label:'Interrupt',vi:'Cung ngắt một nhịp đòn. Một lần thử mỗi chuỗi; enemy một nhịp cần timing khi áp sát.',en:'Bow cancels one beat. One attempt per chain; single-beat enemies require timing during approach.'};
TERM_HELP['follow-up']={label:'Follow-up',vi:'Tap một lần để nối hai nhát dao. Né sẽ hủy những nhát chưa trúng.',en:'One tap adds two dagger hits. Dodging cancels unlanded hits.'};
TERM_HELP.guardstance={label:'Guard Stance',vi:'Đại kiếm có thể chặn một hit hoặc tiêu thụ thế để bổ mạnh. Không cộng dồn; cần một Clean Chain để hồi.',en:'Greatsword can block one hit or spend stance for a heavy strike. No stacking; restore with one Clean Chain.'};
TERM_HELP.cleanchain={label:'Clean Chain',vi:'Tránh hoặc Deflect thành công mọi nhịp trong chuỗi. Không yêu cầu tất cả đều Perfect Dodge. Bị trúng rồi dùng Thế đỡ chặn không tính.',en:'Avoid or deflect every beat successfully. Not every beat needs Perfect Dodge. Taking a hit protected by guard does not count.'};
TERM_HELP.perfect.label='Perfect Dodge';
TERM_HELP.perfectdodge=TERM_HELP.perfect;
const termPopup=document.createElement('dialog');termPopup.id='term-popup';termPopup.hidden=true;termPopup.setAttribute('role','dialog');termPopup.setAttribute('aria-label','Keyword');document.body.append(termPopup);
function showTerm(key,target){const term=TERM_HELP[key];if(!term)return;termPopup.replaceChildren();const title=document.createElement('strong'),text=document.createElement('p'),close=document.createElement('button');title.textContent=term.label;text.textContent=locale==='vi'?term.vi:term.en;close.textContent='×';close.setAttribute('aria-label',locale==='vi'?'Đóng':'Close');close.onclick=closeTerm;termPopup.append(title,close,text);termPopup.hidden=false;termPopup.wasPaused=paused;paused=true;if(!termPopup.open)termPopup.showModal();target.setAttribute('aria-describedby','term-popup');}
function decorateTerms(){const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT),nodes=[];let n;while(n=walker.nextNode()){if(n.parentElement.closest('script,style,svg,button,select,summary,#mastery-title,[data-term],#term-popup')||!n.nodeValue.trim())continue;if(/\b(Clean Chain|Perfect Dodge|Deflect|Interrupt|Follow-up|Guard Stance|Sức bền|Sơ hở|Giáp ảo|Stamina|Opening|Guard|Giữ đúng|Hit bank|Flow|Perfect|Normal|Mastery|Aim|Charge|shield|DMG|Damage|XP|Gold|HP|Fire|Ice|Lightning|Burn|Chill|Sét|Băng|Lửa)\b/i.test(n.nodeValue))nodes.push(n);}for(const node of nodes){const fragment=document.createDocumentFragment(),text=node.nodeValue,pattern=/\b(Clean Chain|Perfect Dodge|Deflect|Interrupt|Follow-up|Guard Stance|Sức bền|Sơ hở|Giáp ảo|Stamina|Opening|Guard|Giữ đúng|Hit bank|Flow|Perfect|Normal|Mastery|Aim|Charge|shield|DMG|Damage|XP|Gold|HP|Fire|Ice|Lightning|Burn|Chill|Sét|Băng|Lửa)\b/gi;let at=0,m;while(m=pattern.exec(text)){fragment.append(text.slice(at,m.index));const term=document.createElement('span');term.dataset.term=({'sứcbền':'stamina','sơhở':'opening','giápảo':'guard','giữđúng':'hold','sét':'lightning','băng':'ice','lửa':'fire','dmg':'damage'}[m[0].toLowerCase().replace(' ','')]||m[0].toLowerCase().replace(' ',''));term.className='keyword';term.tabIndex=0;term.setAttribute('role','button');term.textContent=m[0];fragment.append(term);at=m.index+m[0].length;}fragment.append(text.slice(at));node.replaceWith(fragment);}}
document.addEventListener('click',e=>{const term=e.target.closest('[data-term]');if(term){e.stopPropagation();showTerm(term.dataset.term,term);}else if(termPopup.open&&!e.target.closest('#term-popup'))closeTerm();},true);
function closeTerm(){if(!termPopup.open)return;termPopup.close();termPopup.hidden=true;paused=termPopup.wasPaused===true;previous=performance.now();}
termPopup.addEventListener('cancel',e=>{e.preventDefault();closeTerm();});termPopup.addEventListener('click',e=>{if(e.target===termPopup){const r=termPopup.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeTerm();}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&termPopup.open)closeTerm();const term=e.target.closest('[data-term]');if(term&&['Enter',' '].includes(e.key)){e.preventDefault();showTerm(term.dataset.term,term);}});
const buildButton=document.createElement('button');buildButton.id='active-build';buildButton.textContent='✦';buildButton.setAttribute('aria-label','Skill đang có / Current skills');$('#flow-label').after(buildButton);
const buildDialog=document.createElement('dialog');buildDialog.id='build-dialog';buildDialog.innerHTML='<div class="build-head"><h2></h2><button aria-label="Close">×</button></div><div class="build-content"></div>';document.body.append(buildDialog);buildDialog.querySelector('button').onclick=()=>buildDialog.close();
buildButton.onclick=()=>{const root=buildDialog.querySelector('.build-content');root.replaceChildren();buildDialog.querySelector('h2').textContent=locale==='vi'?'Skill đang có':'Current skills';const weapon=document.createElement('p');weapon.textContent=weaponLabel(game.weapon)+' · Mastery Lv.'+game.level;root.append(weapon);const resource=document.createElement('p');resource.className='build-resource';resource.textContent=game.weaponRulesVersion?WEAPONS[game.weapon].state+' · '+(locale==='vi'?'Sức bền enemy ':'Enemy stamina ')+game.stamina+'/'+game.staminaMax:game.weapon==='daggers'?'Hit bank '+game.bank+'/4':game.weapon==='greatsword'?'Charge '+game.charge+'/'+(game.level>=2?3:2):game.weapon==='bow'?'Aim '+game.aim+'/2':'Perfect '+game.perfects+' · Flow '+game.flow;root.append(resource);for(let i=0;i<2;i++)if(game.level>=i+2){const row=document.createElement('article');row.className='equipped-skill';row.innerHTML=weaponIcon(game.weapon)+'<div><strong>'+translateText(WEAPONS[game.weapon].upgrades[i].split(':')[0])+' · Mastery Lv.'+(i+2)+'</strong><p>'+translateText(WEAPONS[game.weapon].upgrades[i].split(':').slice(1).join(':'))+'</p></div>';root.append(row);}for(const [id,rank]of Object.entries(game.skills)){const card=document.createElement('article');card.className='equipped-skill';card.innerHTML=skillIconMarkup(id)+`<div><strong>${skillLabel(id)} · Lv.${rank}</strong><small>${EXTRA_SKILLS[id]?.weapon?(locale==='vi'?'Phản công vũ khí':'Weapon counter'):EXTRA_SKILLS[id]?.element?(locale==='vi'?'Nguyên tố phản công':'Counter element'):(locale==='vi'?'Chiến kỹ bị động':'Passive Battle Art')}</small><p>${translateText(SKILLS[id].desc[rank-1])}</p></div>`;root.append(card);}if(!Object.keys(game.skills).length){const note=document.createElement('p');note.textContent=locale==='vi'?'Chưa chọn skill cho lượt này.':'No skills selected for this run.';root.append(note);}buildDialog.showModal();decorateTerms();};
buildDialog.addEventListener('close',()=>{if(game.state==='combat')previous=performance.now();});
// Keep a combat tell frozen while inspecting the build, preserving the current beat.
buildButton.addEventListener('click',()=>{buildDialog.dataset.wasPaused=String(paused);paused=true;});buildDialog.addEventListener('close',()=>paused=buildDialog.dataset.wasPaused==='true');
const eventDialog=document.createElement('dialog');eventDialog.id='event-dialog';eventDialog.innerHTML='<div class="event-seal">◇</div><h2></h2><p class="event-intro"></p><div class="event-options"></div>';document.body.append(eventDialog);
eventDialog.addEventListener('cancel',e=>e.preventDefault());
function renderEventDialog(){const active=game.state==='event';$('#state-panel').classList.toggle('event-behind',active);if(!active){if(eventDialog.open)eventDialog.close();return;}if(eventDialog.open)return;eventDialog.querySelector('h2').textContent=locale==='vi'?'Người lữ hành':'The traveler';eventDialog.querySelector('.event-intro').textContent=locale==='vi'?'Giữa đường núi, một người lạ đưa ra ba lựa chọn. Chọn một rồi tiếp tục hành trình.':'On the mountain path, a stranger offers three choices. Choose one, then continue.';const root=eventDialog.querySelector('.event-options');root.replaceChildren();const choices=[['safe','→',locale==='vi'?'Đi tiếp':'Continue',locale==='vi'?'Giữ HP và Gold. Không nhận thưởng.':'Keep HP and Gold. No reward.'],['risk','♥',locale==='vi'?'Đánh đổi':'Trade',locale==='vi'?'−1 HP → +5 Gold. Giữ ít nhất 1 HP.':'−1 HP → +5 Gold. Keep at least 1 HP.'],['supplies','◇',locale==='vi'?'Mua hộ vệ':'Buy protection',locale==='vi'?'−2 Gold → 1 Shield. Chặn một lần trúng đòn.':'−2 Gold → 1 Shield. Block one hit.']];for(const [id,icon,title,description]of choices){const b=document.createElement('button');b.innerHTML=`<span class="event-choice-icon">${icon}</span><span><strong>${title}</strong><small>${description}</small></span>`;b.disabled=id==='risk'&&game.hp<=1||id==='supplies'&&(game.meta.gold<2||game.shield>0);b.onclick=()=>{if(game.chooseEvent(id)){eventDialog.close();mobileSignature=panelSignature='';}};root.append(b);}const summary=document.createElement('p');summary.className='event-wallet';summary.textContent='♥ '+game.hp+'/3 · '+game.meta.gold+' Gold · '+game.shield+' Shield';root.append(summary);eventDialog.showModal();decorateTerms();}
const originalMobileUI=mobileUI;mobileUI=function(){originalMobileUI();buildButton.textContent='✦ '+Object.keys(game.skills).length;renderEventDialog();};
const originalLocalize=localizeUI;localizeUI=function(){originalLocalize();decorateTerms();};

buildDialog.addEventListener('click',e=>{if(e.target!==buildDialog)return;const r=buildDialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)buildDialog.close();});
