const MOBILE_NODES={swordsman:['⚔ Swordsman','Combat · 2 Gold','Thắng nhận 2 Gold và chọn một skill.'],heavy_knight:['♜ Heavy Knight','Combat · 2 Gold','Nhiều HP hơn, báo đòn chậm hơn.'],rest:['☕ Rest','Hồi 1 HP','Hồi 1 HP, tối đa 3.'],shrine:['✦ Shrine','Nâng skill','Nâng một skill đang có, tối đa Lv.2.'],event:['? Sự kiện','Lựa chọn đánh đổi','Chọn nhận 2 Gold an toàn, hoặc mất 1 HP để nhận 5 Gold. Không thể đánh đổi HP cuối cùng.'],rogue:['⚔ Rogue','Combat · 2 Gold','Đối thủ nhanh. Thắng nhận skill.'],shop:['◇ Shop','Skill · 2 Gold','Mua hoặc nâng skill với 2 Gold. Có thể bỏ qua.'],treasure:['▣ Kho báu','3 Gold','Nhận 3 Gold, không chiến đấu.'],duelist:['♟ Elite','4 Gold + skill','Trận khó hơn, phần thưởng tốt hơn.'],camp:['☕ Trại trước boss','Hồi 1 HP','Hồi HP thay vì đánh Elite; bỏ qua Gold và skill từ Elite.'],boss:['♛ Boss','10 Gold','Chọn boss. Thắng kết thúc dungeon.']};
const SKILL_COLORS={flame_counter:'#f09a50',momentum:'#64d2e3',bloodlust:'#e6748d',guardian:'#86cfa5',focus:'#ae8cdf'};
function drawSkills(ctx,g){const recent=g.skillEvents.filter(e=>g.time-e.time<2.4).slice(-3);recent.forEach((e,i)=>{const age=g.time-e.time,c=SKILL_COLORS[e.id]||'#e9d399';ctx.save();ctx.globalAlpha=Math.min(1,(2.4-age)*2);ctx.fillStyle='#193e48ed';ctx.fillRect(70,60+i*47-age*8,810,40);ctx.fillStyle=c;ctx.font='bold 30px system-ui';ctx.fillText(e.text,88,90+i*47-age*8);ctx.strokeStyle=c;ctx.lineWidth=5;ctx.beginPath();if(e.id==='guardian')ctx.ellipse(300,355,65,75,0,0,Math.PI*2);else if(e.id==='focus')ctx.arc(300,345,80,-Math.PI/2,Math.PI);else ctx.ellipse(300,425,65,15,0,0,Math.PI*2);ctx.stroke();for(let j=0;j<6;j++){ctx.fillStyle=c;ctx.beginPath();ctx.arc(300+Math.sin(age*5+j)*65,410-age*40-j*5,4,0,Math.PI*2);ctx.fill();}ctx.restore();});}
let mobileSignature='',chosenNode=null,tutorialStep=-1,lastTutorialDodges=0;
function mobileUI(){const dialogOpen=$('#drawer').open||$('#node-dialog').open||$('#help-dialog').open;if(dialogOpen)return;$('#flow-label').textContent='Flow '+game.flow;$('#gold-label').textContent='◇ '+game.meta.gold;$('#enemy-name').textContent=game.state==='combat'||game.test?game.enemy.name+' · '+game.enemyHp+'/'+game.enemyMax+(game.isBoss?' · P'+game.phase:''):'Thành cổ';$('#enemy-fill').style.width=(100*game.enemyHp/game.enemyMax)+'%';$('#short-stats').textContent=WEAPONS[game.weapon].name+' · Damage '+(game.lastDamage||'—')+(game.test?' · TEST':'');
 const signature=game.state+game.floor+JSON.stringify(game.log)+game.hp+game.meta.gold;
 if(signature!==mobileSignature){mobileSignature=signature;$('#route-map').hidden=game.state!=='route';if(game.state==='route')buildMap();if(game.state==='event'){stateCards.replaceChildren();$('#state-title').textContent='Sự kiện · Người lữ hành';$('#state-desc').textContent='Chọn an toàn hoặc đánh đổi HP để lấy thêm Gold.';const risk=button('Đánh đổi 1 HP → 5 Gold','Giữ ít nhất 1 HP',()=>game.chooseEvent('risk'));risk.disabled=game.hp<=1;stateCards.append(button('Nhận 2 Gold','Không mất HP',()=>game.chooseEvent('safe')),risk);}}
 if(tutorialStep>=0){$('#short-stats').textContent=['Bước 1 · Chạm UP khi vòng gần đầy','Bước 2 · Chạm DOWN khi vòng gần đầy','Bước 3 · Chạm JUMP qua quét chân'][tutorialStep]||'Hoàn thành hướng dẫn!';if(game.dodged>lastTutorialDodges){lastTutorialDodges=game.dodged;tutorialStep++;if(tutorialStep===3){tutorialStep=-1;game.feedback='Đã học đủ 3 cách né!';auto=false;}else nextAttack=game.time+1.2;}if(tutorialStep>=0&&!game.attack&&!game.action&&!game.counter&&!game.shots.some(s=>!s.hit)&&game.time>=nextAttack){game.begin(['up','down','jump'][tutorialStep]);nextAttack=game.time+3;}if(game.hp<3)game.hp=3;}
}
function buildMap(){const root=$('#route-map');root.replaceChildren();const tip=document.createElement('p');tip.textContent='Vuốt ngang để xem đường · Chạm node sáng để xem chi tiết';root.append(tip);const scroll=document.createElement('div');scroll.className='map-scroll';const columns=document.createElement('div');columns.className='map-columns';ROUTE.forEach((ids,index)=>{const col=document.createElement('div');col.className='map-column';const label=document.createElement('label');label.textContent='T'+(index+1);col.append(label);ids.forEach(id=>{const n=MOBILE_NODES[id],b=button(n[0],n[1],()=>openNode(id));b.className='map-node'+(game.log.includes(id)?' selected':index===game.floor?' available':'');b.disabled=index!==game.floor;col.append(b);});columns.append(col);});scroll.append(columns);root.append(scroll);const history=document.createElement('p');history.textContent=game.log.length?'Đã đi: '+game.log.map(id=>MOBILE_NODES[id][0]).join(' → '):'Chọn encounter đầu tiên.';root.append(history);requestAnimationFrame(()=>{scroll.scrollLeft=Math.max(0,game.floor*158-55);});}
function openNode(id){chosenNode=id;$('#node-title').textContent=MOBILE_NODES[id][0];$('#node-description').textContent=MOBILE_NODES[id][2];$('#boss-choice').hidden=id!=='boss';$('#boss-choice').replaceChildren();if(id==='boss')for(const [key,b]of Object.entries(BOSSES)){const btn=button(b.name,b.hp+' HP · '+b.phases+' phase',()=>{game.bossId=key;$('#boss-choice').querySelectorAll('button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');});btn.classList.toggle('active',key===game.bossId);$('#boss-choice').append(btn);}paused=true;$('#node-dialog').showModal();}
$('#confirm-node').onclick=()=>{if(chosenNode){game.selectNode(chosenNode);nextAttack=game.time+1;mobileSignature='';}$('#node-dialog').close();paused=false;};$('#cancel-node').onclick=()=>{$('#node-dialog').close();paused=false;};$('#node-dialog').addEventListener('cancel',()=>{paused=false;});
$('#open-menu').onclick=()=>{paused=true;$('#drawer').showModal();};$('#close-menu').onclick=()=>{$('#drawer').close();paused=false;previous=performance.now();};$('#drawer').addEventListener('cancel',()=>{paused=false;previous=performance.now();});$('#drawer').addEventListener('click',()=>{updateUI();mobileSignature='';});
$('#tutorial').onclick=()=>{$('#drawer').close();$('#help-dialog').showModal();};$('#close-help').onclick=()=>{$('#help-dialog').close();paused=false;};$('#help-dialog').addEventListener('cancel',()=>{paused=false;});$('#start-tutorial').onclick=()=>{$('#help-dialog').close();game.enterTest('bow','heavy_knight');game.enemyHp=game.enemyMax=100;tutorialStep=0;lastTutorialDodges=0;auto=selfPlay=false;nextAttack=game.time+1;paused=false;syncToggles();};
// Stop the encounter while the app is backgrounded; return through the pause menu.
document.addEventListener('visibilitychange',()=>{if(document.hidden&&game.state==='combat'){paused=true;if(!$('#drawer').open&&!$('#node-dialog').open&&!$('#help-dialog').open)$('#drawer').showModal();}});

for(const id of ['home','reset','test-toggle','spawn-enemy','spawn-boss'])$('#'+id).addEventListener('click',()=>{tutorialStep=-1;});
