const MOBILE_NODES={swordsman:['⚔ Swordsman','Combat · 2 Gold','Thắng nhận 2 Gold và chọn một skill.'],heavy_knight:['♜ Heavy Knight','Combat · 2 Gold','Nhiều HP hơn, báo đòn chậm hơn.'],rest:['☕ Rest','Hồi 1 HP','Hồi 1 HP, tối đa 3.'],shrine:['✦ Shrine','Nâng skill','Nâng một skill đang có, tối đa Lv.2.'],event:['? Sự kiện','Lựa chọn đánh đổi','Chọn nhận 2 Gold an toàn, hoặc mất 1 HP để nhận 5 Gold. Không thể đánh đổi HP cuối cùng.'],rogue:['⚔ Rogue','Combat · 2 Gold','Đối thủ nhanh. Thắng nhận skill.'],shop:['◇ Shop','Skill · 2 Gold','Mua hoặc nâng skill với 2 Gold. Có thể bỏ qua.'],treasure:['▣ Kho báu','3 Gold','Nhận 3 Gold, không chiến đấu.'],duelist:['♟ Elite','4 Gold + skill','Trận khó hơn, phần thưởng tốt hơn.'],camp:['☕ Trại trước boss','Hồi 1 HP','Hồi HP thay vì đánh Elite; bỏ qua Gold và skill từ Elite.'],boss:['♛ Boss','10 Gold','Chọn boss. Thắng kết thúc dungeon.']};
const SKILL_COLORS={flame_counter:'#f09a50',momentum:'#64d2e3',bloodlust:'#e6748d',guardian:'#86cfa5',focus:'#ae8cdf'};
let mobileSignature='',chosenNode=null,tutorialStep=-1,lastTutorialDodges=0;
function mobileUI(){const dialogOpen=$('#drawer').open||$('#node-dialog').open||$('#help-dialog').open;if(dialogOpen)return;$('#flow-label').textContent='Flow '+game.flow;$('#gold-label').textContent='◇ '+game.meta.gold;$('#enemy-name').textContent=game.state==='combat'||game.test?game.enemy.name+' · '+game.enemyHp+'/'+game.enemyMax+(game.isBoss?' · P'+game.phase:''):'Thành cổ';$('#enemy-fill').style.width=(100*game.enemyHp/game.enemyMax)+'%';$('#short-stats').textContent=WEAPONS[game.weapon].name+' · Damage '+(game.lastDamage||'—')+(game.test?' · TEST':'');
 const signature=game.state+game.floor+JSON.stringify(game.log)+game.hp+game.meta.gold;
 if(signature!==mobileSignature){mobileSignature=signature;$('#route-map').hidden=game.state!=='route';if(game.state==='route')buildMap();if(game.state==='event'){stateCards.replaceChildren();$('#state-title').textContent='Sự kiện · Người lữ hành';$('#state-desc').textContent='Chọn an toàn hoặc đánh đổi HP để lấy thêm Gold.';const risk=button('Đánh đổi 1 HP → 5 Gold','Giữ ít nhất 1 HP',()=>game.chooseEvent('risk'));risk.disabled=game.hp<=1;stateCards.append(button('Nhận 2 Gold','Không mất HP',()=>game.chooseEvent('safe')),risk);}}
 lessons.update(game);updateLessonUI();
}
function openNode(id){chosenNode=id;$('#node-title').textContent=ROOM_ROSTERS[id]?ENEMIES[game.roomEnemy(id)].name+' · '+MOBILE_NODES[id][1]:MOBILE_NODES[id][0];$('#node-description').textContent=nodeDetails(id)+' · HP hiện tại '+game.hp+'/3 · Gold '+game.meta.gold;$('#boss-choice').hidden=id!=='boss';$('#boss-choice').replaceChildren();if(id==='boss')for(const [key,b]of Object.entries(BOSSES)){const btn=button(b.name,b.hp+' HP · '+b.phases+' phase',()=>{game.bossId=key;$('#boss-choice').querySelectorAll('button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');});btn.classList.toggle('active',key===game.bossId);$('#boss-choice').append(btn);}paused=true;$('#node-dialog').showModal();}
$('#confirm-node').onclick=()=>{if(chosenNode){game.selectNode(chosenNode);nextAttack=game.time+1;mobileSignature='';}$('#node-dialog').close();paused=false;};$('#cancel-node').onclick=()=>{$('#node-dialog').close();paused=false;};$('#node-dialog').addEventListener('cancel',()=>{paused=false;});
$('#open-menu').onclick=()=>{paused=true;$('#drawer').showModal();};$('#close-menu').onclick=()=>{$('#drawer').close();paused=false;previous=performance.now();};$('#drawer').addEventListener('cancel',()=>{paused=false;previous=performance.now();});$('#drawer').addEventListener('click',()=>{updateUI();mobileSignature='';});
$('#tutorial').onclick=()=>{$('#drawer').close();$('#help-dialog').showModal();};$('#close-help').onclick=()=>{$('#help-dialog').close();paused=false;};$('#help-dialog').addEventListener('cancel',()=>{paused=false;});$('#start-tutorial').onclick=()=>{$('#help-dialog').close();startLessons();};
const lessons=new LessonController();
function startLessons(){lessons.start(game);auto=selfPlay=false;paused=false;syncToggles();}
function updateLessonUI(){const active=lessons.active;$('#lesson-panel').hidden=!active;if(!active)return;const lesson=LESSONS[lessons.step];$('#lesson-title').textContent=lesson.title;$('#lesson-hint').textContent=lesson.hint;$('#lesson-result').textContent=lessons.message;$('#lesson-next').hidden=!lessons.waiting;$('#lesson-next').disabled=!!(game.combo||game.action||game.counter||game.shots.some(s=>!s.hit));$('#lesson-next').textContent=lessons.step===LESSONS.length-1?'Hoàn thành':'Bài tiếp';}
$('#lesson-next').onclick=()=>{lessons.next(game);updateLessonUI();};
$('#lesson-exit').onclick=()=>{lessons.stop();game.testTempo='standard';game.reset();auto=selfPlay=false;syncToggles();updateLessonUI();};

// Stop the encounter while the app is backgrounded; return through the pause menu.
document.addEventListener('visibilitychange',()=>{if(document.hidden&&game.state==='combat'){paused=true;if(!$('#drawer').open&&!$('#node-dialog').open&&!$('#help-dialog').open)$('#drawer').showModal();}});

for(const id of ['home','reset','test-toggle','spawn-enemy','spawn-boss'])$('#'+id).addEventListener('click',()=>{lessons.stop();updateLessonUI();});

function updateTurnUI(){const a=game.attack,c=game.combo;$('#turn-hud').hidden=!game.test||!$('#test-turns').checked||game.state!=='combat';$('#turn-hud').textContent='Lượt '+(game.attackCount||0)+' · Đòn '+(a?Math.min(a.index+1||1,a.count||1):'—')+'/'+(a?.count||c?.hits?.length||1)+(game.counter?' · Phản công':'');const last=game.lastCombo;if(last)$('#turn-result').textContent=last.results.map((r,i)=>'Đòn '+(i+1)+': '+(r.kind==='jump'?'Đập đất':r.family==='ranged'?'Tầm xa': ['Trên','Giữa','Dưới'][r.target])+' · '+(r.safe?r.perfect?'Perfect':'Normal':'Trúng đòn')).join(' → ');}

function updateProcUI(){const events=game.skillEvents.filter(e=>game.time-e.time<2.1);$('#proc-toast').hidden=!events.length;$('#proc-toast').textContent=events.map(e=>e.text.replace('thành công','✓')).join(' · ');}

function nodeDetails(id){if(ROOM_ROSTERS[id]){const e=ENEMIES[game.roomEnemy(id)];return e.name+' · '+e.hp+' HP · '+(id==='duelist'?'4 Gold + skill':'2 Gold + skill')+' · '+(BEAST_IDS.includes(game.roomEnemy(id))?'Áp sát, móng vuốt và chấn động.':'Quan sát vũ khí để đọc đòn.');}if(['rest','camp'].includes(id))return game.hp===3?'HP đã đầy: nhận 1 shield, chặn một lần trúng đòn.':'Hồi 1 HP. '+(id==='camp'?'Đổi lấy việc bỏ qua 4 Gold và skill từ Elite.':'Bỏ qua nâng skill hoặc sự kiện.');return MOBILE_NODES[id][2];}
$('#test-tempo').onchange=()=>{game.testTempo=$('#test-tempo').value;applyTestRules();};
if(window.REVIEW_VIEW==='lessons')startLessons();
if(window.REVIEW_VIEW==='readability'||window.REVIEW_VIEW==='beasts'){game.enterTest('bow',window.REVIEW_VIEW==='beasts'?'iron_bear':'duelist');game.enemyHp=game.enemyMax=100;game.testLength=3;auto=true;selfPlay=true;if(window.REVIEW_VIEW==='readability')$('#test-turns').checked=false;nextAttack=game.time+1;syncToggles();}
if(window.REVIEW_VIEW==='tuning'){game.enterTest('bow','elder_bear',true);game.enemyMax=90;game.enemyHp=20;game.testLength=4;auto=selfPlay=true;nextAttack=game.time+1;syncToggles();}
if(window.REVIEW_VIEW==='routes'){startRun();game.selectSkill('momentum');}
