function masteryProgress(meta,w,rank){const p=ensureProgress(meta),r=MASTERY_RULES[rank];return (p.legacyRanks[w]||1)>=rank?[1,1,locale==='vi'?'Đã mở từ bản trước':'Unlocked in the previous version']:[p.xp[w]||0,r.xp,'XP encounter'];}
function collectionIsOpen(row){for(const w of Object.keys(WEAPONS))for(let i=0;i<2;i++)if(row.id===w+i)return masteryRank(game.meta,w)>=i+2;return row.progress[0]>=row.progress[1];}
extraProgress=function(meta,id){return EXTRA_SKILLS[id]?unlockProgress(meta,id):null;};
collectionProgress=function(meta,id){return unlockProgress(meta,id);};
const progressionCollection=renderCollection;renderCollection=function(){progressionCollection();const root=document.querySelector('#collection-content');if(collectionTab==='shared'||root.querySelector('.mastery-summary'))return;const p=ensureProgress(game.meta),w=collectionTab,rank=masteryRank(game.meta,w),box=document.createElement('div');box.className='mastery-summary';box.innerHTML='<strong>'+weaponLabel(w)+' · Mastery Lv.'+rank+'</strong>';const summary=document.createElement('p');summary.textContent=locale==='vi'?'Thắng trận: 1 XP · Elite: 2 · Boss: 4. Dungeon 1: '+(p.tiers[w][1]||0)+'/24 XP.':'Win: 1 XP · Elite: 2 · Boss: 4. Dungeon 1: '+(p.tiers[w][1]||0)+'/24 XP.';box.append(summary);for(const [lv,r]of Object.entries(MASTERY_RULES)){const line=document.createElement('p'),q=qualifiedXP(p,w,r.dungeon);line.textContent='Lv.'+lv+': '+Math.min(p.xp[w],r.xp)+'/'+r.xp+' XP · '+Math.min(q,r.qualified)+'/'+r.qualified+' XP '+(locale==='vi'?'từ':'from')+' Dungeon '+r.dungeon+'+'+(rank>=+lv?' ✓':'');box.append(line);}const keep=document.createElement('small');keep.textContent=locale==='vi'?'Cấp đã mở giữ khi chơi lại. Dungeon 2–6 chưa phát hành.':'Unlocked ranks persist on replay. Dungeons 2–6 are not released.';box.append(keep);if((p.legacyRanks[w]||1)>1){const legacy=document.createElement('p');legacy.textContent=locale==='vi'?'Cấp '+p.legacyRanks[w]+' đã mở từ bản trước được giữ. XP mới bắt đầu riêng.':'Rank '+p.legacyRanks[w]+' from the previous version is retained. New XP is tracked separately.';box.append(legacy);}root.querySelector('.collection-guide-links').after(box);};
const progressionDetail=showCollectionSkill;showCollectionSkill=function(row){progressionDetail(row);if(row.weaponGuide)return;const dialog=document.querySelector('#collection-detail'),p=ensureProgress(game.meta);for(const w of Object.keys(WEAPONS))for(let i=0;i<2;i++)if(row.id===w+i){const r=MASTERY_RULES[i+2],note=document.createElement('p');note.textContent=locale==='vi'?'Cần thêm điều kiện: '+Math.min(qualifiedXP(p,w,r.dungeon),r.qualified)+'/'+r.qualified+' XP từ Dungeon '+r.dungeon+'+. Cấp này giữ vĩnh viễn.':'Additional requirement: '+Math.min(qualifiedXP(p,w,r.dungeon),r.qualified)+'/'+r.qualified+' XP from Dungeon '+r.dungeon+'+. This rank is permanent.';dialog.append(note);}if(SKILL_UNLOCKS[row.id]){const note=document.createElement('p');note.textContent=locale==='vi'?'Mở khóa vĩnh viễn chỉ thêm vào nhóm có thể chọn. Mỗi lượt phải chọn/mua lại; tối đa 4 skill, trong đó tối đa 1 nguyên tố. Shop: lấy skill mới hoặc nâng skill đang có; Shrine: chỉ nâng skill đang có.':'Unlocking adds a permanent option, not an equipped skill. Choose/buy it each run. Up to 4 skills, including 1 element. Shops offer new skills or upgrades; shrines only upgrade owned skills.';dialog.append(note);}};
const progressionUIStyle=document.createElement('style');progressionUIStyle.textContent='.mastery-summary{border:1px solid #8c9b7b;border-radius:10px;padding:9px 12px;margin:7px 0 10px;color:#efdbac}.mastery-summary p{font-size:11px;line-height:1.4;margin:4px 0}.mastery-summary small{font-size:10px;color:#b4c8c6}#mastery-reward{font-size:11px;color:#e8d397;text-align:center;flex-shrink:0}';document.head.append(progressionUIStyle);
const masteryReward=document.createElement('div');masteryReward.id='mastery-reward';document.querySelector('#turn-damage-summary').after(masteryReward);
function progressionRewardUI(){const r=game.lastMasteryReward,active=!game.test&&r&&['reward','won'].includes(game.state);masteryReward.hidden=!active;if(active){const text='Mastery +'+r.amount+' XP'+(r.capped?(locale==='vi'?' · Dungeon 1 đã đạt giới hạn':' · Dungeon 1 XP cap reached'):'');if(masteryReward.textContent!==text)masteryReward.textContent=text;}requestAnimationFrame(progressionRewardUI);}requestAnimationFrame(progressionRewardUI);

