const MAP_LABELS={swordsman:'Kiếm sĩ',heavy_knight:'Hiệp sĩ',rest:'Nơi trú',shrine:'Đền cổ',event:'Lữ hành',rogue:'Phục kích',shop:'Thương nhân',treasure:'Di vật',duelist:'Tinh anh',camp:'Trại cuối',boss:'Lãnh chúa'};
let atlasObserver=null;
function buildMap(){
 atlasObserver?.disconnect();
 const root=$('#route-map');root.replaceChildren();$('#state-title').textContent='Hành trình · '+(game.floor+1)+' / '+game.route.length;
 const region=ROUTE_REGIONS.find(r=>game.floor>=r.from&&game.floor<=r.to)||ROUTE_REGIONS[0],head=document.createElement('div');head.className='atlas-heading';head.innerHTML='<span>CHƯƠNG '+(ROUTE_REGIONS.indexOf(region)+1)+'</span><strong>'+region.name+'</strong><small>'+region.subtitle+'</small>';root.append(head);
 if(game.routeOutcome){const notice=document.createElement('p');notice.className='route-outcome';notice.textContent=game.routeOutcome;root.append(notice);}
 const tip=document.createElement('p');tip.className='atlas-tip';tip.textContent='Theo đường nối · Chạm điểm sáng để xem đánh đổi';root.append(tip);
 const scroll=document.createElement('div');scroll.className='vertical-map-scroll';const map=document.createElement('div');map.className='vertical-map atlas-map';map.style.minHeight=(game.route.length*153+70)+'px';map.innerHTML=mapLandscapeMarkup();const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('map-links');svg.setAttribute('aria-hidden','true');map.append(svg);
 const allowed=game.availableNodes();game.route.forEach((ids,tier)=>{
  const row=document.createElement('div');row.className='map-tier';row.dataset.tier=tier;
  if(tier%3===0){const band=document.createElement('span');band.className='map-region-label';band.textContent=ROUTE_REGIONS[Math.floor(tier/3)]?.name||'';row.append(band);}
  const label=document.createElement('span');label.className='tier-label';label.textContent=String(tier+1).padStart(2,'0');row.append(label);const group=document.createElement('div');group.className='tier-nodes';
  ids.forEach((id,index)=>{const available=tier===game.floor&&allowed.includes(id),visited=game.log[tier]===id,name=MAP_LABELS[id];const b=button('',null,()=>openNode(id));b.className='route-node'+(visited?' visited':available?' available':'')+(id==='duelist'?' danger-node':'');b.dataset.node=id;b.dataset.tier=tier;b.dataset.index=index;b.disabled=!available;b.setAttribute('aria-label','Chặng '+(tier+1)+' · '+name+(available?' · có thể chọn':''));b.title=nodeDetails(id,tier);
   const icon=document.createElement('span');icon.className='node-icon';icon.innerHTML=mapNodeIcon(id);const text=document.createElement('span');text.className='node-name';text.textContent=name;const reward=document.createElement('small');reward.className='node-reward';reward.textContent=({rest:'+HP / shield',camp:'+HP / shield',shop:'2 Gold',event:'Đánh đổi',treasure:'+3 Gold',duelist:'+6 Gold',boss:'+10 Gold',shrine:'Lv. II'})[id]||'+2 Gold';b.append(icon,text,reward);if(visited){const mark=document.createElement('span');mark.className='node-check';mark.textContent='✓';b.append(mark);}group.append(b);
  });row.append(group);map.append(row);
 });scroll.append(map);root.append(scroll);
 const layout=()=>{svg.replaceChildren();const base=map.getBoundingClientRect();svg.setAttribute('viewBox','0 0 '+base.width+' '+base.height);const coords=b=>{const r=b.getBoundingClientRect();return {x:r.left-base.left+r.width/2,y:r.top-base.top+31}};
  for(let tier=0;tier<game.route.length-1;tier++){const current=[...map.querySelectorAll('.route-node[data-tier="'+tier+'"]')],next=[...map.querySelectorAll('.route-node[data-tier="'+(tier+1)+'"]')];current.forEach((a,i)=>next.forEach((b,j)=>{if(game.routeVersion!==1&&!routeConnected(game.route,tier,i,j))return;const p=coords(a),q=coords(b),mid=(p.y+q.y)/2,visited=game.log[tier]===a.dataset.node&&game.log[tier+1]===b.dataset.node,open=tier===game.floor-1&&game.log[tier]===a.dataset.node&&allowed.includes(b.dataset.node);const line=document.createElementNS(svg.namespaceURI,'path');line.setAttribute('d',`M ${p.x} ${p.y} C ${p.x} ${mid} ${q.x} ${mid} ${q.x} ${q.y}`);line.setAttribute('class',visited?'path-visited':open?'path-open':'path-future');svg.append(line);}));}
  const active=map.querySelector('.available');if(active)scroll.scrollTop=Math.max(0,active.getBoundingClientRect().top-scroll.getBoundingClientRect().top+scroll.scrollTop-scroll.clientHeight*.65);
 };atlasObserver=new ResizeObserver(()=>requestAnimationFrame(layout));atlasObserver.observe(scroll);requestAnimationFrame(()=>requestAnimationFrame(layout));
}
