const assert=require('node:assert/strict');global.LaneGame=require('../web-2d/lane-core.js');Object.assign(global,require('../web-2d/full-core.js'));global.CombatGame=require('../web-2d/combat-core.js').CombatGame;const {CampaignGame,BEAST_IDS,ROOM_ROSTERS}=require('../web-2d/campaign-core.js');const {LessonController,LESSONS}=require('../web-2d/lesson-core.js');const {attackSoundCue}=require('../web-2d/feedback.js');let checks=0;const ok=(v,m)=>{assert.ok(v,m);checks++;};
function play(g){if(g.attack&&!g.attack.resolved&&!g.action&&g.time>=g.attack.impact-.45){const k=g.recommendedAction();if(k)g.act(k);}g.update(.02);}
for(const weapon of Object.keys(WEAPONS))for(let rotation=0;rotation<3;rotation++){let seed=rotation+5;const g=new CampaignGame(()=>{seed=(seed*1664525+1013904223)>>>0;return seed/2**32;});g.meta.wins=rotation;g.start(weapon);g.bossId=rotation===2?'elder_bear':'executioner';g.selectSkill('momentum');for(let i=0;i<50000&&g.state!=='won';i++){if(g.state==='route')g.selectNode(['swordsman','swordsman','rogue','heavy_knight','duelist','heavy_knight','rogue','duelist','boss'][g.floor]);if(['reward','shrine','shop'].includes(g.state)){if(!g.selectSkill('momentum'))g.skip();}if(g.state==='combat'&&!g.attack&&!g.combo&&!g.counter&&!g.shots.some(s=>!s.hit))g.begin();play(g);}ok(g.state==='won'&&g.hp===3,weapon+' complete rotated run');ok(g.runGold===34,'Nine-room combat route grants exact Gold across roster variants');ok(g.meta.wins===rotation+1,'Exactly one victory');}
for(const id of BEAST_IDS)for(const tempo of ['slow','standard','challenge']){const g=new CampaignGame();g.enterTest('bow',id,id==='elder_bear');g.testTempo=tempo;g.testLength=4;const prior=JSON.stringify(g.meta);for(let n=0;n<20;n++){g.enemyHp=1000;g.begin();ok(g.combo.interval>=1.4,'Recovery-safe interval');for(let i=0;i<1000&&(g.combo||g.counter||g.shots.some(s=>!s.hit)||g.attack||g.action);i++)play(g);ok(g.hp===3,'Beast chain safe at '+tempo);}ok(JSON.stringify(g.meta)===prior,'Test isolation');}
const g=new CampaignGame();const lesson=new LessonController();lesson.start(g);const before=JSON.stringify(g.meta);for(let step=0;step<LESSONS.length;step++){for(let i=0;i<2000&&(!lesson.waiting||g.combo||g.counter||g.action||g.shots.some(s=>!s.hit));i++){lesson.update(g);play(g);}ok(lesson.waiting,'Lesson accepted '+step);ok(lesson.next(g),'Lesson advances only after counter '+step);}ok(!lesson.active,'All five lessons complete');ok(JSON.stringify(g.meta)===before,'Lessons do not award progression');
const hold=new CampaignGame();lesson.start(hold);lesson.step=3;hold.beginChain(LESSONS[3].hits);hold.update(.01);ok(!lesson.next(hold),'Cannot skip uncompleted lesson');
const rest=new CampaignGame();rest.start();rest.selectSkill('guardian');rest.state='route';rest.floor=3;rest.shield=0;rest.selectNode('rest');ok(rest.hp===3&&rest.shield===1,'Full HP rest grants shield');rest.state='shop';rest.meta.gold=0;ok(!rest.selectSkill('guardian'),'Cannot buy locked starter upgrade without gold');rest.meta.gold=2;ok(rest.selectSkill('guardian')&&rest.skills.guardian===2&&rest.meta.gold===0,'Owned starter skill upgrades correctly');
const cues=[0,1,2].map(target=>attackSoundCue({family:'melee',kind:'melee',target}).freq);ok(new Set(cues).size===3,'Three melee audio signatures');ok(attackSoundCue({kind:'jump'}).freq<Math.min(...cues),'Slam audio separate');for(const ids of Object.values(ROOM_ROSTERS))for(const id of ids)ok(!!ENEMIES[id],'Valid route enemy');
for(const fps of [20,30,60])for(const tempo of ['slow','standard','challenge']){const g=new CampaignGame();g.enterTest('bow','elder_bear',true);g.testTempo=tempo;g.testLength=4;for(let turn=0;turn<8;turn++){g.enemyHp=999;g.begin();for(let i=0;i<fps*20&&(g.combo||g.attack||g.action||g.counter||g.shots.some(s=>!s.hit));i++){if(g.attack&&!g.attack.resolved&&!g.action&&g.time>=g.attack.impact-.45){const k=g.recommendedAction();if(k)g.act(k);}g.update(1/fps);}ok(g.hp===3,'Campaign FPS '+fps+' '+tempo);}}
console.log(checks+' campaign, tutorial, three route rosters, beast chains and cue checks passed');

// Map economy: mutually exclusive purchases, no duplicate payout, and no lethal event trade.
for(const gold of [0,1,2,10]){const g=new CampaignGame();g.state='shop';g.hp=2;g.meta.gold=gold;const before=g.floor;const bought=g.buySupplies();ok(bought===(gold>=2),'Affordable potion');ok(g.hp===(gold>=2?3:2),'Potion heal cap');ok(g.floor===before+(gold>=2?1:0),'One room advance');ok(!g.buySupplies(),'Cannot repurchase after exit');}
{const g=new CampaignGame();g.state='shop';g.hp=3;g.meta.gold=10;ok(!g.buySupplies()&&g.meta.gold===10,'Full HP cannot spend potion gold');g.state='event';g.hp=1;ok(!g.chooseEvent('risk')&&g.hp===1,'Event cannot spend last HP');ok(g.chooseEvent('supplies')&&g.meta.gold===8&&g.shield===1,'Buy one shield');ok(!g.chooseEvent('supplies')&&g.meta.gold===8,'No repeated event purchase');}
{const g=new CampaignGame();g.state='route';g.floor=5;const before=g.meta.gold;ok(g.selectNode('treasure')&&g.meta.gold===before+3,'Treasure payout');ok(!g.selectNode('treasure')&&g.meta.gold===before+3,'Treasure cannot pay twice');}
console.log('Map purchases and repeat-reward guards passed');
