const assert=require('node:assert/strict');global.LaneGame=require('../web-2d/lane-core.js');const {FullGame,WEAPONS,ENEMIES,BOSSES}=require('../web-2d/full-core.js');let count=0;const ok=x=>{assert.ok(x);count++};
function step(g){if(g.state==='starter')g.selectSkill('focus');if(g.state==='route')g.selectNode(['swordsman','rest','rogue','duelist','boss'][g.floor]);if(g.state==='reward'){const id=['focus','flame_counter','momentum','guardian','bloodlust'].find(id=>g.unlocked(id)&&(g.skills[id]||0)<2);if(!id||!g.selectSkill(id))g.skip();}if(g.state==='combat'&&!g.attack&&!g.counter&&!g.shots.some(s=>!s.hit))g.begin(g.nextKind());if(g.attack&&!g.attack.resolved&&!g.action&&g.time>=g.attack.impact-.45)g.act(g.attack.kind);g.update(.02);}
for(const weapon of Object.keys(WEAPONS))for(const boss of Object.keys(BOSSES)){const g=new FullGame();g.bossId=boss;g.start(weapon);for(let i=0;i<18000&&g.state!=='won';i++)step(g);ok(g.state==='won'&&g.hp===3);ok(g.meta.wins===1&&g.meta.gold===18&&g.meta.xp[weapon]>0);const xp=g.meta.xp[weapon];g.update(10);ok(g.meta.xp[weapon]===xp&&g.meta.gold===18);}
for(const weapon of Object.keys(WEAPONS))for(const enemy of [...Object.keys(ENEMIES),...Object.keys(BOSSES)]){const g=new FullGame();g.enterTest(weapon,enemy,!!BOSSES[enemy]);g.testLevel=3;const before=JSON.stringify(g.meta);for(let i=0;i<18000&&g.state!=='test-won';i++)step(g);ok(g.state==='test-won'&&g.hp===3);ok(JSON.stringify(g.meta)===before);}
const g=new FullGame();g.start('bow');ok(!g.selectSkill('momentum'));ok(g.selectSkill('focus'));ok(!g.selectNode('boss'));ok(g.selectNode('heavy_knight'));g.shield=1;g.begin('jump');g.update(2.2);ok(g.hp===3&&g.shield===0);g.begin('jump');g.update(2.2);ok(g.hp===2);
const shop=new FullGame();shop.start();shop.selectSkill('focus');shop.floor=2;shop.state='route';shop.selectNode('shop');ok(!shop.selectSkill('flame_counter'));shop.meta.gold=2;ok(shop.selectSkill('flame_counter')&&shop.meta.gold===0&&shop.floor===3);shop.skills.flame_counter=2;shop.state='shrine';ok(!shop.selectSkill('flame_counter'));
const dmg=new FullGame();dmg.enterTest('greatsword');dmg.testLevel=3;ok(dmg.damage(false,true)===1&&dmg.charge===1);ok(dmg.damage(false,true)===1&&dmg.charge===2);ok(dmg.damage(false,true)===1&&dmg.charge===3);ok(dmg.damage(true,true)===5&&dmg.charge===0);dmg.weapon='daggers';ok(dmg.damage(true,true)===3&&dmg.bank===0);dmg.weapon='bow';dmg.aim=2;ok(dmg.damage(true,true)===4&&dmg.aim===0);
console.log(count+' full dungeon / weapon / test-isolation checks passed');

